=== haenaleapxd/kaerus-group/wp-content/themes/kicks/editor/schema/module-schema.json
{
  "title": "JSON schema for XD Modules",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "attributes": {
      "$ref": "https://schemas.wp.org/trunk/block.json#/properties/attributes"
    }
  },
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "description": "Panel title"
    },
    "className": {
      "type": "string",
      "description": "Panel class"
    },
    "initialOpen": {
      "type": "boolean",
      "description": "Whether the panel should be open by default"
    },
    "name": {
      "type": "string",
      "description": "Module name"
    },
    "supports": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Support Name",
            "pattern": "xd/.+|^anchor$"
          },
          "attributes": {
            "type": "object",
            "patternProperties": {
              "[a-zA-Z]": {
                "type": "object",
                "properties": {
                  "type": {
                    "oneOf": [
                      {
                        "type": "string",
                        "enum": ["null", "boolean", "object", "array", "string", "integer", "number"]
                      },
                      {
                        "type": "array",
                        "uniqueItems": true,
                        "items": {
                          "type": "string",
                          "enum": ["null", "boolean", "object", "array", "string", "integer", "number"]
                        }
                      }
                    ]
                  },
                  "className": {
                    "oneOf": [
                      {
                        "type": "object",
                        "default": {},
                        "patternProperties": {
                          "[a-zA-Z]": {
                            "description": "The key refers to a property of the attribute when the attribute is an object. When true is selected, the selected property value will be applied to the block class. When a string literal is entered, the string will be applied to the block class when the property value is true",
                            "oneOf": [
                              {
                                "type": "boolean",
                                "default": true
                              },
                              {
                                "type": "string",
                                "default": ""
                              }
                            ]
                          }
                        }
                      },
                      {
                        "description": "When set to true, the attribute value will be applied to the className",
                        "type": "boolean",
                        "default": false
                      },
                      {
                        "description": "This string will be applied to the attribute when the attribute value is true",
                        "type": "string",
                        "default": ""
                      }
                    ]
                  },
                  "cssTransform": {
                    "type": "object",
                    "default": {},
                    "description": "Defines a transformation pattern for outputting a css variable. The key can be either a regular expression for string type attributes, or an object key for an object type attribute",
                    "patternProperties": {
                      "[a-zA-Z]": {
                        "oneOf": [
                          {
                            "description": "The regular expression and replacement pattern, or the object key to perform replacement on",
                            "type": "string",
                            "default": ""
                          },
                          {
                            "description": "The name of the attributes object key for which the css attribute should be transformed",
                            "type": "object",
                            "patternProperties": {
                              ".*": {
                                "description": "The regular expression and replacement pattern",
                                "type": "string",
                                "default": ""
                              },
                              "default": {}
                            }
                          }
                        ]
                      }
                    }
                  },
                  "cssVariable": {
                    "description": "Output the attribute as a css variable in the blocks style attribute",
                    "type": "boolean"
                  }
                }
              }
            }
          },
          "inspectorControls": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["attribute", "type"],
              "properties": {
                "attribute": {
                  "type": "string",
                  "description": "Name is used for data storage on block"
                },
                "label": {
                  "type": "string"
                },
                "type": {
                  "anyOf": [
                    {
                      "default": "XDImageControl"
                    },
                    {
                      "default": "XDCheckboxGroup"
                    },
                    {
                      "default": "XDFileUploadControl"
                    },
                    {
                      "default": "XDButtonGroup"
                    },
                    {
                      "default": "XDRadioButtonGroup"
                    },
                    {
                      "default": "TextControl"
                    },
                    {
                      "default": "TextareaControl"
                    },
                    {
                      "default": "SelectControl"
                    },
                    {
                      "default": "RangeControl"
                    },
                    {
                      "default": "ToggleControl"
                    },
                    {
                      "default": "DateTimePicker"
                    },
                    {
                      "default": "XDFieldGroup"
                    }
                  ],
                  "type": "string",
                  "description": "For all types, See https://developer.wordpress.org/block-editor/reference-guides/components/"
                },
                "activeState": {
                  "type": "string",
                  "description": "The field property that should receive its state. Eg. 'value', or 'checked'",
                  "default": "value"
                },
                "exposeProps": {
                  "type": "boolean",
                  "description": "Forwards all props through to component rather than just primitive props like value and onChange"
                },
                "method": {
                  "type": "string",
                  "description": "The event that is fired when the field changes. Eg  onChange, or onClick"
                }
              }
            }
          },
          "blockControls": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["attribute", "type"],
              "properties": {
                "attribute": {
                  "type": "string",
                  "description": "Name is used for data storage on block"
                },
                "group": {
                  "type": "string",
                  "description": "Name of group in toolbar. Use th same name on multiple toolbar controls to show them in the same group"
                },
                "title": {
                  "type": "string"
                },
                "type": {
                  "anyOf": [
                    {
                      "default": "XDLinkToolBarButton"
                    }
                  ],
                  "type": "string",
                  "description": "For all types, See https://developer.wordpress.org/block-editor/reference-guides/components/"
                },
                "activeState": {
                  "type": "string",
                  "description": "The field property that should receive its state. Eg. 'value', or 'checked'",
                  "default": "value"
                },
                "exposeProps": {
                  "type": "boolean",
                  "description": "Forwards all props through to component rather than just primitive props like value and onChange"
                },
                "method": {
                  "type": "string",
                  "description": "The event that is fired when the field changes. Eg  onChange, or onClick"
                }
              }
            }
          }
        }
      }
    }
  },
  "required": ["name"]
}

=== haenaleapxd/kaerus-group/wp-content/themes/kicks/editor/modules/margin.json
{
	"$schema": "../schema/module-schema.json",
	"title": "Margin",
	"name": "margin",
	"initialOpen": true,
	"supports": [{
			"name": "xd/margin",
			"attributes": {
				"marginTop": {
					"type": "string",
					"default": "xd-mt--lg",
					"className": true
				},
				"marginBottom": {
					"type": "string",
					"default": "xd-mb--lg",
					"className": true
				}
			}
		},
		{
			"name": "xd/margin-controls",
			"inspectorControls": [{
					"type": "XDRadioButtonGroup",
					"label": "Top",
					"attribute": "marginTop",
					"options": [{
							"label": "None",
							"value": ""
						},
						{
							"label": "Small",
							"value": "xd-mt--sm"
						},
						{
							"label": "Large",
							"value": "xd-mt--lg"
						}
					]
				},
				{
					"type": "XDRadioButtonGroup",
					"label": "Bottom",
					"attribute": "marginBottom",
					"options": [{
							"label": "None",
							"value": ""
						},
						{
							"label": "Small",
							"value": "xd-mb--sm"
						},
						{
							"label": "Large",
							"value": "xd-mb--lg"
						}
					]
				}
			]
		}
	]
}

=== haenaleapxd/kaerus-group/wp-content/themes/kaerus-group/editor/modules/color-theme.json
{
	"$schema": "../../../../themes/kicks/editor/schema/module-schema.json",
  "title": "Color Theme",
  "name": "color-theme",
  "initialOpen": true,
  "supports": [
    {
      "name": "xd/color-theme",
      "attributes": {
        "colorTheme": {
          "type": "string",
          "default": "is-style-dark",
          "className": {
            "is-style-light": "is-style-light has-background-color",
            "is-style-medium": "is-style-medium has-background-color",
            "is-style-dark": "is-style-dark has-background-default"
          }
        }
      },
      "inspectorControls": [
        {
          "type": "XDButtonGroup",
          "attribute": "colorTheme",
          "options": [
            {
              "label": "Light",
              "value": "is-style-light"
            },
            {
              "label": "Medium",
              "value": "is-style-medium"
            },
            {
              "label": "Dark",
              "value": "is-style-dark"
            }
          ]
        }
      ]
    }
  ]
}

=== haenaleapxd/kaerus-group/wp-content/themes/kicks/editor/modules/padding.json
{
  "$schema": "../schema/module-schema.json",
  "title": "Padding",
  "name": "padding",
  "initialOpen": true,
  "supports": [
    {
      "name": "xd/padding",
      "attributes": {
        "paddingTop": {
          "type": "string",
          "default": "xd-pt--sm",
          "className": true
        },
        "paddingBottom": {
          "type": "string",
          "default": "xd-pb--sm",
          "className": true
        }
      }
    },
    {
      "name": "xd/padding-controls",
      "inspectorControls": [
        {
          "type": "XDRadioButtonGroup",
          "label": "Top",
          "attribute": "paddingTop",
          "options": [
            {
              "label": "None",
              "value": ""
            },
            {
              "label": "Small",
              "value": "xd-pt--sm"
            },
            {
              "label": "Large",
              "value": "xd-pt--lg"
            }
          ]
        },
        {
          "type": "XDRadioButtonGroup",
          "label": "Bottom",
          "attribute": "paddingBottom",
          "options": [
            {
              "label": "None",
              "value": ""
            },
            {
              "label": "Small",
              "value": "xd-pb--sm"
            },
            {
              "label": "Large",
              "value": "xd-pb--lg"
            }
          ]
        }
      ]
    },
    {
      "name": "xd/padding-controls-all",
      "inspectorControls": [
        {
          "type": "XDRadioButtonGroup",
          "label": "Top",
          "attribute": "paddingTop",
          "options": [
            {
              "label": "None",
              "value": ""
            },
            {
              "label": "Tiny",
              "value": "xd-pt--xs"
            },
            {
              "label": "Small",
              "value": "xd-pt--sm"
            },
            {
              "label": "Large",
              "value": "xd-pt--lg"
            }
          ]
        },
        {
          "type": "XDRadioButtonGroup",
          "label": "Bottom",
          "attribute": "paddingBottom",
          "options": [
            {
              "label": "None",
              "value": ""
            },
            {
              "label": "Tiny",
              "value": "xd-pb--xs"
            },
            {
              "label": "Small",
              "value": "xd-pb--sm"
            },
            {
              "label": "Large",
              "value": "xd-pb--lg"
            }
          ]
        }
      ]
    },
    {
      "name": "xd/padding-controls-tiny",
      "inspectorControls": [
        {
          "type": "XDRadioButtonGroup",
          "label": "Top",
          "attribute": "paddingTop",
          "options": [
            {
              "label": "None",
              "value": ""
            },
            {
              "label": "Tiny",
              "value": "xd-pt--xs"
            }
          ]
        },
        {
          "type": "XDRadioButtonGroup",
          "label": "Bottom",
          "attribute": "paddingBottom",
          "options": [
            {
              "label": "None",
              "value": ""
            },
            {
              "label": "Tiny",
              "value": "xd-pb--xs"
            }
          ]
        }
      ]
    }
  ]
}

=== haenaleapxd/kaerus-group/wp-content/themes/kicks/editor/modules/card-slider-width.json
{
  "$schema": "../../editor/schema/module-schema.json",
  "title": "Display",
  "name": "card-slider",
  "initialOpen": true,
  "supports": [
    {
      "name": "xd/card-slider-width",
      "attributes": {
        "wideWidth": {
          "type": "boolean",
          "default": false
        }
      },
      "inspectorControls": [
        {
          "attribute": "wideWidth",
          "type": "XDRadioButtonGroup",
          "label": "Width",
          "options": [
            { "label": "Standard", "value": false },
            { "label": "Wide", "value": true }
          ]
        }
      ]
    }
  ]
}

=== haenaleapxd/kaerus-group/wp-content/themes/kicks/editor/modules/color-theme.json
{
  "$schema": "../schema/module-schema.json",
  "title": "Color Theme",
  "name": "color-theme",
  "initialOpen": true,
  "supports": [
    {
      "name": "xd/color-theme",
      "attributes": {
        "colorTheme": {
          "type": "string",
          "default": "is-style-light",
          "className": {
            "is-style-light": "is-style-light has-background-default",
            "is-style-medium": "is-style-medium has-background-color",
            "is-style-dark": "is-style-dark has-background-color"
          }
        }
      },
      "inspectorControls": [
        {
          "type": "XDButtonGroup",
          "attribute": "colorTheme",
          "options": [
            {
              "label": "Light",
              "value": "is-style-light"
            },
            {
              "label": "Medium",
              "value": "is-style-medium"
            },
            {
              "label": "Dark",
              "value": "is-style-dark"
            }
          ]
        }
      ]
    }
  ]
}

=== haenaleapxd/kaerus-group/wp-content/themes/kicks/editor/modules/button-style.json
{
  "$schema": "../schema/module-schema.json",
  "title": "Button Style",
  "name": "button-style",
  "initialOpen": true,
  "supports": [
    {
      "name": "xd/button-style",
      "attributes": {
        "buttonStyle": {
          "type": "string",
          "default": "xd-button--primary",
          "className": true
        },
        "invertColor": {
          "type": "boolean",
          "className": "xd-button--invert"
        }
      }
    },
    {
      "name": "xd/button-style-controls",
      "inspectorControls": [
        {
          "attribute": "buttonStyle",
          "type": "XDButtonGroup",
          "options": [
            {
              "label": "Primary",
              "value": "xd-button--primary"
            },
            {
              "label": "Ghost",
              "value": "xd-button--ghost"
            },
            {
              "label": "Inverse",
              "value": "xd-button--inverse"
            },
            {
              "label": "Ghost Inverse",
              "value": "xd-button--ghost-inverse"
            },
            {
              "label": "Download",
              "value": "xd-button--download xd-button--text"
            },
            {
              "label": "Text",
              "value": "xd-button--text"
            }
          ]
        }
      ]
    },
    {
      "name": "xd/button-style-controls-v2",
      "inspectorControls": [
        {
          "attribute": "buttonStyle",
          "type": "XDButtonGroup",
          "options": [
            {
              "label": "Primary",
              "value": "xd-button--primary"
            },
            {
              "label": "Ghost",
              "value": "xd-button--ghost"
            },
            {
              "label": "Download",
              "value": "xd-button--download xd-button--text"
            },
            {
              "label": "Text",
              "value": "xd-button--text"
            }
          ]
        }
      ]
    },
    {
      "name": "xd/button-style-invert",
      "inspectorControls": [
        {
          "attribute": "invertColor",
          "type": "ToggleControl",
          "label": "Invert colors",
          "activeState": "checked"
        }
      ]
    }
  ]
}

=== haenaleapxd/kaerus-group/wp-content/themes/kicks/editor/modules/video.json
{
  "$schema": "../schema/module-schema.json",
  "title": "Video",
  "name": "video",
  "initialOpen": true,
  "supports": [
    {
      "name": "xd/video",
      "attributes": {
        "videoMobile": {
          "type": "object",
          "default": {
            "id": "",
            "url": "",
            "width": "",
            "height": "",
            "orientation": ""
          },
          "className": {
            "url": "xd-video--mobile"
          }
        },
        "videoTablet": {
          "type": "object",
          "default": {
            "id": "",
            "url": "",
            "width": "",
            "height": "",
            "orientation": ""
          },
          "className": {
            "url": "xd-video--tablet"
          }
        },
        "videoDesktop": {
          "type": "object",
          "default": {
            "id": "",
            "url": "",
            "width": "",
            "height": "",
            "orientation": ""
          },
          "className": {
            "url": "xd-video--desktop"
          }
        }
      },
      "inspectorControls": [
        {
          "label": "Desktop Video",
          "type": "XDVideoControl",
          "attribute": "videoDesktop"
        },
        {
          "label": "Tablet Video",
          "type": "XDVideoControl",
          "attribute": "videoTablet",
          "help": "Video cropped for tablet devices"
        },
        {
          "label": "Mobile Video",
          "type": "XDVideoControl",
          "attribute": "videoMobile",
          "help": "Video cropped for mobile devices"
        }
      ]
    },
    {
      "name": "xd/video-modal",
      "attributes": {
        "videoModal": {
          "type": "object",
          "default": {
            "title": "",
            "url": "",
            "rel": "",
            "target": ""
          }
        }
      },
      "inspectorControls": [
        {
          "type": "XDEmbedControl",
          "name": "videoModal",
          "label": "Modal Video",
          "attribute": "videoModal",
          "help": "Enter a streaming URL. Eg. Vimeo or YouTube",
          "settings": []
        }
      ]
    }
  ]
}

=== haenaleapxd/kaerus-group/wp-content/themes/kicks/editor/modules/image.json
{
  "$schema": "../schema/module-schema.json",
  "title": "Image",
  "name": "image",
  "initialOpen": true,
  "supports": [
    {
      "name": "xd/image-video-message",
      "inspectorControls": [
        {
          "attribute": "none",
          "type": "XDMessagePanel",
          "label": "Video Poster image",
          "help": "The poster image will will be displayed while the video is buffering. The video size will be determined by the dimensions of the poster image"
        }
      ]
    },
    {
      "name": "xd/image-desktop",
      "attributes": {
        "imageDesktop": {
          "type": "object",
          "default": {
            "id": "",
            "url": ""
          }
        },
        "showCaption": {
          "type": "boolean",
          "default": true
        }
      },
      "inspectorControls": [
        {
          "label": "Primary image",
          "type": "XDImageControl",
          "attribute": "imageDesktop"
        },
        {
          "label": "Show caption",
          "type": "ToggleControl",
          "activeState": "checked",
          "attribute": "showCaption"
        }
      ]
    },
    {
      "name": "xd/image-mobile",
      "attributes": {
        "imageMobile": {
          "type": "object",
          "default": {
            "id": "",
            "url": ""
          }
        }
      },
      "inspectorControls": [
        {
          "label": "Mobile Crop",
          "type": "XDImageControl",
          "attribute": "imageMobile",
          "help": "(Optional) image cropped for mobile devices"
        }
      ]
    },
    {
      "name": "xd/image-align",
      "attributes": {
        "imageAlign": {
          "type": "string",
          "default": "alignleft",
          "className": true
        }
      },
      "blockControls": [
        {
          "label": "Align Image",
          "attribute": "imageAlign",
          "type": "XDToolbarDropdownMenu",
          "group": "image-align",
          "options": [
            {
              "iconPosition": "left",
              "icon": "wp/positionLeft",
              "label": "Left",
              "value": "alignleft"
            },
            {
              "iconPosition": "left",
              "icon": "wp/positionCenter",
              "label": "Center",
              "value": "aligncenter"
            },
            {
              "iconPosition": "left",
              "icon": "wp/positionRight",
              "label": "Right",
              "value": "alignright"
            }
          ]
        }
      ]
    },
    {
      "name": "xd/image-width",
      "attributes": {
        "imageWidth": {
          "type": "string",
          "default": "100%",
          "cssVariable": true
        }
      },
      "inspectorControls": [
        {
          "label": "Image Width",
          "type": "XDWidthControl",
          "attribute": "imageWidth"
        }
      ]
    }
  ]
}
